"""K3's route, generalised exactly, applied to K4 + Quagmire III with an UNKNOWN alphabet.

Fact (verified below on the real K3 texts): K3's two-grid route (rows of 42 read
columns bottom->top, then rows of 14 read the same way) is the index map
    (CT position + 1) = 192 * (PT position + 1)  mod 337,   192 = 8 * 24 (row counts), 337 = 336 + 1.
In general one full-grid pass with r rows multiplies (position + 1) by r modulo n + 1.
So "K3's method on another block" is a CLOSED family of multipliers, not a free route.

Model A ('?' belongs to K4): n = 98, modulus 99, full grids have r in {2, 7, 14, 49} rows,
    any number of passes -> multipliers in the group generated by {2, 7} mod 99.
    The carved '?' sits at CT position 0, which DETERMINES where the null was in the plaintext.
Model B (97 letters): modulus 98 has no full grid (97 is prime); the natural
    generalisation is decimation x -> m x mod 98, gcd(m, 98) = 1 (42 multipliers).

Each permutation is combined with Quagmire III (unknown alphabet), periodic key p = 1..26,
Vigenere and Beaufort senses, substitution before or after the transposition.
Null control: random ciphertexts, run for every (multiplier, order, mode) where K4 is SAT
at a short period (p <= 13). Positive control: synthetic ciphertexts built with the mechanism.

Run: python3 k3_multiplicative.py
"""
import json
import random
import sys
from math import gcd

from k4_algebraic import AZ, ANCH, K4, K3PT, Model, _alph, _relation


def k3_route(seq, w):
    rows = (len(seq) + w - 1) // w
    return [seq[r * w + c] for c in range(w) for r in range(rows - 1, -1, -1) if r * w + c < len(seq)]


def verify_k3():
    ct = "".join(k3_route(k3_route(list(K3PT), 42), 14))
    assert ct.startswith("ENDYAHROHNLSRHEOCPTEOIBI"), ct[:24]
    idx = k3_route(k3_route(list(range(336)), 42), 14)          # ct[t] = PT[idx[t]]
    assert all((t + 1) % 337 == 192 * (i + 1) % 337 for t, i in enumerate(idx))
    for r, w in ((8, 42), (24, 14), (7, 48)):
        one = k3_route(list(range(336)), w)
        assert all((t + 1) % 337 == r * (i + 1) % 337 for t, i in enumerate(one))
    return True


def q3_periodic(triples, mode, p):
    """triples: (ct_letter, pt_letter, key_index). Quagmire III, unknown alphabet."""
    m = Model()
    P, C = _alph(m, "III")
    for c, q, k in triples:
        _relation(m, P, C, c, q, [(1, f"k{k % p}")], mode)
    return m.solve()


def triples_A(ct98, anch97, mult, order):
    """Model A. CT98[t] = PT98[i] with (t+1) = mult*(i+1) mod 99. Null = PT98 index of t=0."""
    inv = pow(mult, -1, 99)
    src = [(inv * (t + 1)) % 99 - 1 for t in range(98)]          # PT98 index at CT position t
    q = src[0]                                                   # null position in PT98
    ctpos = {i: t for t, i in enumerate(src)}
    out = []
    for j, ch in anch97.items():
        i = j if j < q else j + 1
        t = ctpos[i]
        # key runs over the 97 letters: CT letter index t-1 (TS) or PT letter index j (ST)
        out.append((ct98[t], ch, (t - 1) if order == "TS" else j))
    return out, q


def triples_B(ct97, anch97, mult, order):
    inv = pow(mult, -1, 98)
    src = [(inv * (t + 1)) % 98 - 1 for t in range(97)]
    ctpos = {i: t for t, i in enumerate(src)}
    return [(ct97[ctpos[j]], ch, ctpos[j] if order == "TS" else j) for j, ch in anch97.items()]


def group_mod(gens, n):
    g, frontier = {1}, [1]
    while frontier:
        x = frontier.pop()
        for s in gens:
            y = x * s % n
            if y not in g:
                g.add(y)
                frontier.append(y)
    return sorted(g)


def rand_ct(seed, n=97):
    r = random.Random(seed)
    return "".join(r.choice(AZ) for _ in range(n))


def synth_B(mult, order, mode, seed=3, period=10):
    r = random.Random(seed)
    Pa = r.sample(range(26), 26)
    inv_a = {v: k for k, v in enumerate(Pa)}
    key = [r.randrange(26) for _ in range(period)]
    pt = [r.choice(AZ) for _ in range(97)]
    for j, ch in ANCH.items():
        pt[j] = ch
    sg = 1 if mode == "vig" else -1

    def sub(ch, k):
        return AZ[inv_a[(sg * Pa[AZ.index(ch)] + key[k % period]) % 26]]
    dst = [(mult * (i + 1)) % 98 - 1 for i in range(97)]         # PT index i -> CT position
    ct = [None] * 97
    for i in range(97):
        ct[dst[i]] = pt[i] if order == "TS" else sub(pt[i], i)
    if order == "TS":
        ct = [sub(ct[t], t) for t in range(97)]
    return "".join(ct)


def main():
    res = {"K3_identity_verified": verify_k3()}
    GA = group_mod([2, 7], 99)
    MB = [m for m in range(1, 98) if gcd(m, 98) == 1]
    res["modelA_multipliers"] = GA
    res["modelB_multipliers"] = MB
    print("K3 route == multiplication by 192 mod 337: verified")
    print(f"Model A: {len(GA)} multipliers {GA}")
    print(f"Model B: {len(MB)} multipliers")

    # positive controls (Model B, 3 multipliers x orders x modes)
    pc = {}
    for mult in (3, 5, 13):
        for order in ("TS", "ST"):
            for mode in ("vig", "beau"):
                ct = synth_B(mult, order, mode)
                tr = triples_B(ct, ANCH, mult, order)
                pc[f"m{mult}-{order}-{mode}"] = [q3_periodic(tr, mode, 10), q3_periodic(tr, mode, 7)]
    res["positive_controls_B_[p10,p7]"] = pc
    print("positive controls (want [True, False]):", pc, flush=True)

    ct98 = "?" + K4
    shard, nshard = (int(sys.argv[1]), int(sys.argv[2])) if len(sys.argv) > 2 else (0, 1)
    for model, mults in (("A", GA[shard::nshard]), ("B", MB[shard::nshard])):
        rows = []
        for mult in mults:
            for order in ("TS", "ST"):
                if model == "A":
                    tr, q = triples_A(ct98, ANCH, mult, order)
                else:
                    tr, q = triples_B(K4, ANCH, mult, order), None
                for mode in ("vig", "beau"):
                    sat = [p for p in range(1, 27) if q3_periodic(tr, mode, p)]
                    row = {"mult": mult, "order": order, "mode": mode, "null_pos_PT98": q, "K4_sat": sat}
                    short = [p for p in sat if p <= 13]
                    if short:          # targeted null for the short-period survivors
                        rates = {}
                        for p in short:
                            hits = 0
                            for s in range(30):
                                rc = rand_ct(4000 + s)
                                if model == "A":
                                    trr, _ = triples_A("?" + rc, ANCH, mult, order)
                                else:
                                    trr = triples_B(rc, ANCH, mult, order)
                                hits += q3_periodic(trr, mode, p)
                            rates[p] = f"{hits}/30"
                        row["null_rate_short"] = rates
                    rows.append(row)
                    if short:
                        print(model, row, flush=True)
        res[f"model{model}"] = rows
        n_short = sum(1 for r in rows if any(p <= 13 for p in r["K4_sat"]))
        print(f"Model {model}: {len(rows)} configurations, {n_short} with a short period (<=13) compatible",
              flush=True)
    suffix = f"_shard{shard}of{nshard}" if nshard > 1 else ""
    with open(f"results_k3_multiplicative{suffix}.json", "w") as f:
        json.dump(res, f, indent=1)


if __name__ == "__main__":
    main()
